import { Artifact } from '@/components/create-artifact';
import { DocumentSkeleton } from '@/components/document-skeleton';
import { Markdown } from '@/components/markdown';

// Client renderer for research-fa-ta documents. Displays markdown content
// generated by the server detailing fundamentals and technical strategy.
export const researchFaTaArtifact = new Artifact<'research-fa-ta'>({
  kind: 'research-fa-ta',
  description: 'Combined fundamental and technical analysis with strategy.',
  initialize: async () => {},
  onStreamPart: ({ streamPart, setArtifact }) => {
    if (streamPart.type === 'data-textDelta') {
      setArtifact((draft) => ({
        ...draft,
        content: draft.content + streamPart.data,
        status: 'streaming',
        isVisible: true,
      }));
    }
  },
  content: ({ content, isLoading }) => {
    if (isLoading) return <DocumentSkeleton artifactKind="text" />;
    return (
      <div className="p-4">
        <Markdown>{content}</Markdown>
      </div>
    );
  },
  actions: [],
  toolbar: [],
});
